# Generated by Django 5.2.7 on 2025-10-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_categoria_producto_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_cat',
            field=models.ImageField(default=1, upload_to='pedidos/images/'),
            preserve_default=False,
        ),
    ]
