# Generated by Django 5.2.7 on 2025-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_producto_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.IntegerField(),
        ),
    ]
